version: '3.9'

services:
  database:
    image: postgres:17.0
    restart: always
    environment:
      POSTGRES_DB: "warehouse_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      backend:
        aliases:
          - "database"

  service:
    build:
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      db_url: jdbc:postgresql://database:5432/warehouse_db
      db_username: postgres
      db_password: "postgres"
      TZ: Europe/Ulyanovsk

    networks:
      backend:
        aliases:
          - "service"

networks:
  backend:
    driver: bridge

volumes:
  postgres_data: