server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${db_url}
    username: ${db_username}
    password: ${db_password}
  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true
springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    path: /v3/api-docs